### ISSUE TITLE
App crashing after submitting form

### ISSUE THREAD

**Issue by hansemannn** [fbsamples/account-kit-samples-for-ios#1]
Hey there! First of all thanks for this great new Framework, it will revolutionize the way we login today. I just created a native module to support AccountKit in Titanium Mobile (850.000+ users), and got the dialogs shown up properly. Unfortunately, the app crashes as soon as I submit the form. Happens with both email- and phone-verification.

The module can be found [here](https://github.com/hansemannn/ti.accountkit), the related source [here](https://github.com/hansemannn/ti.accountkit/blob/master/iphone/Classes/TiAccountkitModule.m#L67).

Thanks in advance!

**Comment by olgaikuznetsova** [comment]
Are you still facing this issue? You submitted some other comments around your app so it sounds like you've gotten past the problem? Are you using the SDK downloaded from the developer documentation here - https://developers.facebook.com/docs/accountkit/ios

**Comment by hansemannn** [comment]
Thanks for the response @olgaikuznetsova! Yes, I'm using the official version. I also notice that delegates do not fire. Is it possible that the Framework currently works if used in View Controllers? As the module is very generic (like [ti.facebook](https://github.com/appcelerator-modules/ti.facebook) for the Facebook SDK), we need to receive delegates independently. I'm sure we can sort this out, thank you!

**Comment by toddkrabach** [comment]
You have defined the delegate methods, but you never set your class as the delegate on the view controller.  You should probably just add a line here (https://github.com/hansemannn/ti.accountkit/blob/master/iphone/Classes/TiAccountkitModule.m#L69):

  viewController.delegate = self;
