### ISSUE TITLE
Invalid OAuth 2.0

### ISSUE THREAD

**Issue by itsaark** [fbsamples/account-kit-samples-for-ios#11]
Hi,
Can we update the UI changes(color & text) from Account Kit console (facebook app dashboard)?

**Comment by mcohnen** [comment]
Hi,
Not at the moment. AccountKit console will only affect the browser login and confirmation email. 
Thank you for the feedback, and we will keep it present for future upgrades of AccountKit.

**Comment by itsaark** [comment]
Thanks for the response. It would be really cool to have that upgrade. Looking forward to it.
