### ISSUE TITLE
Unrecognized Locale when uploading to iTunes Connect

### ISSUE THREAD

**Issue by CooperCodeComposer** [fbsamples/account-kit-samples-for-ios#13]
Hi there,
I recently updated the AccountKit pod from 4.19.0 to 4.22.0. Upon uploading the archive to iTunes Connect a warning appeared saying "Unrecognized Locale..." (see below). 
Rolling back AccountKit to 4.20.0 seemed to fix and the archive uploaded without issue. 
Thank you,
-A
<img width="585" alt="screen shot 2017-05-11 at 6 06 06 pm" src="https://cloud.githubusercontent.com/assets/16313589/26002303/182e6dd4-36e4-11e7-8b3d-49cf55725813.png">

**Comment by mcohnen** [comment]
Thanks for reporting this issue. V.4.22.1 has a fix for it.

**Comment by CooperCodeComposer** [comment]
Great - thank you!
