### ISSUE TITLE
Country Code Placeholder

### ISSUE THREAD

**Issue by girishghoda** [fbsamples/account-kit-samples-for-ios#15]
@jamesgpearce @caabernathy  I have issue in account kit country code place holder
How to fix it? ,attach screenshot kindly check it
Thank you
![attachment-8314462703505914590screenshot-0301-120808](https://user-images.githubusercontent.com/19307918/36960185-daeec780-206b-11e8-9971-1134922a2d70.png)

**Comment by lepouya** [comment]
Hi,

It looks to me that you're missing the string translations from your compiled project. Can you make sure that `AccountKitStrings.bundle` is properly linked and at least the English language strings are included with it?
