### ISSUE TITLE
Show me : A system issue occurred. Please try again.

### ISSUE THREAD

**Issue by IDEAL-YANG** [fbsamples/account-kit-samples-for-ios#17]
I've followed all the steps in there.

I've setup my Info.plist correctly. But waiting for a long time, Show me : A system issue occurred. Please try again. Unbelievable！！！

![1527575856254](https://user-images.githubusercontent.com/11627070/40641893-e0b28ba0-634d-11e8-8d9d-647ce7e139f3.jpg)

**Comment by IDEAL-YANG** [comment]
Debug this : [AccountKit][Error]: Postponing App Events due to error: Error Domain=com.facebook.accountkit:Error Code=100 "(null)" UserInfo={NSUnderlyingError=0x10ae87540 {Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x10ae75000 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://graph.accountkit.com/v1.3/993923234116218/events...

**Comment by IDEAL-YANG** [comment]
Sometimes debug show this : [AccountKit][Error]: Postponing App Events due to error: Error Domain=com.facebook.accountkit:Error Code=100 "(null)" UserInfo={NSUnderlyingError=0x604000443000 {Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x600000446d80 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://graph.accountkit.com/v1.3/993923234116218/events...

**Comment by IDEAL-YANG** [comment]
Sometimes debug show this :[AccountKit][Error]: Postponing App Events due to error: Error Domain=com.facebook.accountkit:Error Code=100 "(null)" UserInfo={NSUnderlyingError=0x11bc8a220 {Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x11bc166c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://graph.accountkit.com/v1.3/993923234116218/events

**Comment by HabelJustin** [comment]
same here.
uses version 1.3 and try to downgrade to 1.2, but still not working
uses on web by the way (accountkit for web)

edit: got this problem if i set display to "modal"

**Comment by IDEAL-YANG** [comment]
Change another vpn fixed. Thanks.

**Comment by HeshanHH** [comment]
0

just because u might not be removed **[]** those brackets... i did the same thing. then i had found this syntax error

**this is wrong-->** `<string name="ACCOUNT_KIT_CLIENT_TOKEN">[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]</string>`

**this is right-->(no BRACKETS)**

`<string name="ACCOUNT_KIT_CLIENT_TOKEN">AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</string>`
