### ISSUE TITLE
An error causes iOS app crashing

### ISSUE THREAD

**Issue by ahsaniqbalbykea** [fbsamples/account-kit-samples-for-ios#22]
Here are the steps to reproduce (STR):

Step 1:
Please enter mobile number and tap Next.
![Screen 1](https://user-images.githubusercontent.com/38309105/54433834-9edfd080-474e-11e9-8f00-db51e30d4948.png)

Step 2:
Please do not enter the SMS code you would most probably have received and tap on **I didn't get a code**.
![Screen 2](https://user-images.githubusercontent.com/38309105/54433872-b7e88180-474e-11e9-94bc-84a4418ee332.png)

Step3:
Tap on **Get a call**.
![Screen 3](https://user-images.githubusercontent.com/38309105/54433879-c0d95300-474e-11e9-8e24-c9f4558f03f8.png)

Step 4:
Please perform steps 2 & 3 again after getting a call and an error is displayed **You've been temporarily blocked from logging in. Please try again later.** Here is the DEBUG result:

Error Domain = com.facebook.accountkit:
Error Code = 200
"(null)" UserInfo = {
    NSUnderlyingError = 0x282507120 {
        Error Domain = com.facebook.accountkit:
        ServerError Code = 15005
        "(null)" UserInfo = {
            com.facebook.accountkit:
            ErrorUserMessageKey = You’ve been temporarily blocked from logging in. Please try again later.,
            com.facebook.accountkit:
            ErrorDeveloperMessageKey = Application does not have permission for this action
        }
    },
    com.facebook.accountkit:
    ErrorUserMessageKey = You’ve been temporarily blocked from logging in. Please try again later.,
    com.facebook.accountkit:
    ErrorDeveloperMessageKey = Application does not have permission for this action
}

Step 5:
Tap on **Try Again** button.
![Screen 4](https://user-images.githubusercontent.com/38309105/54433899-cd5dab80-474e-11e9-987a-415c5f05110f.png)

Step 6:
Tap on **<** button to get back to the previous view.
![Screen 5](https://user-images.githubusercontent.com/38309105/54433908-d3538c80-474e-11e9-9399-8e9279cd382e.png)

Step 7:
Tap on **I didn't get a code** and it causes app crashing.
![Screen 6](https://user-images.githubusercontent.com/38309105/54433942-e49c9900-474e-11e9-8141-8109e0c7a162.png)

**_Note:_**
**_Black highlights has been added to prevent displaying personal information_**

**Comment by robtimp** [comment]
@ahsaniqbalbykea I wasn't able to reproduce this issue. Which version of AccountKit were you experiencing this with? Also, please provide your Xcode version, and installation method and version (e.g. CocoaPods version 1.6.1).

**Comment by ahsaniqbalbykea** [comment]
@robtimp
- AccountKit version [4.35.0](https://github.com/fbsamples/account-kit-samples-for-ios/releases/tag/sdk-version-4.35.0)
- Xcode version [10.1](https://download.developer.apple.com/Developer_Tools/Xcode_10.1/Xcode_10.1.xip)
- Installation method is as it is documented in [3. Set up Your Developer Environment -> Using Cocoapods](https://developers.facebook.com/docs/accountkit/ios#dev-environ-ios)
- CocoaPods version [1.5.3](https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.3)

**Comment by robtimp** [comment]
@ahsaniqbalbykea Please upgrade to the latest version of Account Kit (5.0.0), and the issue should be resolved.
