### ISSUE TITLE
'AccessToken' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by marcellofiore** [fbsamples/account-kit-samples-for-ios#28]
After updating the sdk, I have this error => ('AccessToken' is ambiguous for type lookup in this context)  on method => 
func viewController(viewController: UIViewController!, didCompleteLoginWithAccessToken accessToken: AccessToken!, state: String!)

I want to clarify that: I use it in the same ViewController FBSDKCoreKit and FBSDKLoginKit for facebook Login, if I remove import FBSDKCoreKit and import FBSDKLoginKit the problem is solved.

Can anyone help me?

**Comment by robtimp** [comment]
@marcellofiore Try updating your function signature to the following:

```
func viewController(_ viewController: UIViewController & AKFViewController,
  didCompleteLoginWith accessToken: AccessToken,
  state: String)
```

**Comment by robtimp** [comment]
I'd recommend moving your AKFViewControllerDelegate conformance to a separate file due to the collision between the AccessToken types:

```
// ViewController+AccountKit.swift

import AccountKit

extension ViewController: AKViewControllerDelegate {

  func viewController(_ viewController: UIViewController & AKFViewController, didCompleteLoginWith accessToken: AccessToken, state: String) {
    ...
  }

}
```

Then, remove `import AccountKit` from your current file.

**Comment by danielrobleM** [comment]
I have the same issue and that solution doesn't work for me. Any others solutions ?  @robtimp 
what did you do ? @marcellofiore

**Comment by eduardofiorezi** [comment]
Me too

**Comment by eduardofiorezi** [comment]
Use FBSDKCoreKit.AccessToken

```
func viewController(viewController: UIViewController!, didCompleteLoginWithAccessToken accessToken: FBSDKCoreKit.AccessToken!, state: String!) {
        print("did complete login with access token \(accessToken.tokenString) state \(state)")
    }
```

**Comment by Shrikant-iOS** [comment]
> Use FBSDKCoreKit.AccessToken
> 
> ```
> func viewController(viewController: UIViewController!, didCompleteLoginWithAccessToken accessToken: FBSDKCoreKit.AccessToken!, state: String!) {
>         print("did complete login with access token \(accessToken.tokenString) state \(state)")
>     }
> ```
Instance method 'viewController(_:didCompleteLoginWith:state:)' nearly matches optional requirement 'viewController(_:didCompleteLoginWith:state:)' of protocol 'AKFViewControllerDelegate'

**Comment by robtimp** [comment]
I think this issue here may be that this doesn't match the new method signature for this protocol, which is `func viewController(_ viewController: UIViewController & AKFViewController, didCompleteLoginWith accessToken: AccessToken, state: String)`
