### ISSUE TITLE
I keep getting an OAuth error on iOS [Swift]

### ISSUE THREAD

**Issue by alexbuga** [fbsamples/account-kit-samples-for-ios#3]
Invalid OAuth access token.

I've followed all the steps in there.

I've setup my Info.plist correctly (because FBSDKCoreKit works)
I'm seeing the viewControllerForPhoneLogin but when I submit my phone number I get the Invalid OAuth access token.

**Comment by hansemannn** [comment]
Did you integrate the `AccountKitClientToken` inside your plist? From what I know, it handles the OAuth process.

**Comment by olgaikuznetsova** [comment]
This is the github project for the AccountKit sample - are you having problems running the sample? If this is an issue within your own code, please file a bug with our platform bugs project: https://developers.facebook.com/bugs/

Thank you!

**Comment by toddkrabach** [comment]
alexbuga,

There are a couple of additional Info.plist entries that are required/recommended for AccountKit.  Please see the developer docs (https://developers.facebook.com/docs/accountkit/ios/integrating) for instructions on that.

Thanks,
Todd

**Comment by alexbuga** [comment]
Yeah guys. My Info.plist has e FDBAppID and AccountKit key. Sample works fine. Thanks.
