### ISSUE TITLE
Login with phone: Country Code & localization not recognized

### ISSUE THREAD

**Issue by hansemannn** [fbsamples/account-kit-samples-for-ios#4]
Hey there,

while the [Titanium Mobile module](https://github.com/hansemannn/ti.accountkit) works fine now, I noticed that the country code supplied like below does not work. I would expect that one of `de_DE`, `DE` or `de` preselects the german phone country code `+49`. I didn't find anything related in the docs. Which ISO norm do you expect there? The `AKFPhoneNumber` class is missing all documentation, adding it there would be great.

In addition, in both the example and my generic module, the countries are not localized correctly by default. We need the bundle to localize the current language, but anyway it should fallback to a proper english-localized interface. Thanks!

![simulator screen shot 16 04 2016 21 56 02](https://cloud.githubusercontent.com/assets/10667698/14583303/26916074-041e-11e6-996a-bdf5d6344468.png)
![simulator screen shot 16 04 2016 21 56 05](https://cloud.githubusercontent.com/assets/10667698/14583304/26934948-041e-11e6-84b2-7c6758f57b28.png)

**Comment by olgaikuznetsova** [comment]
Please note that this is the Github page for our samples project, not for the whole of AccountKit. Please file bugs/issues with AccountKit in our developer portal: https://developers.facebook.com/bugs/?tag_ids=1679169675664406

The AFKPhoneNumber reference is here: https://developers.facebook.com/docs/reference/ios/current/class/AKFPhoneNumber/

When you do file, a few questions
1) Are you referring to passing in a default country code or reading it from the device?
2) What language is the device running in?

Thanks!
