### ISSUE TITLE
On back button pressed to remove account kit UI .. viewControllerDidCancel not called 

### ISSUE THREAD

**Issue by priyeshmarvi** [fbsamples/account-kit-samples-for-ios#7]
is this default behavior or is there any delegate called when we remove accountKit UI with back button ... So far I can't get it why `viewControllerDidCancel` not called .. any suggestion or help ?? 

Thanks!!

**Comment by mcohnen** [comment]
Hi! This will be fixed in the next release, which should come out early this week. 
See https://developers.facebook.com/bugs/1631609907166073/

Cheers!
