### ISSUE TITLE
Custom "Inbox Name"

### ISSUE THREAD

**Issue by BilalReffas** [fbsamples/account-kit-samples-for-ios#8]
When I receive a SMS the name Facebook appears. Any chance to customize it in production ?

**Comment by olgaikuznetsova** [comment]
No, the message cannot be customized.

**Comment by BilalReffas** [comment]
On the example app there was a normal number?

**Comment by olgaikuznetsova** [comment]
Sorry, not quite following the question: Do you mean the number the SMS comes from or the number that the SMS is sent?

**Comment by BilalReffas** [comment]
I mean the number where the SMS comes from. Currently there is no number only FACEBOOK will be shown :/

**Comment by olgaikuznetsova** [comment]
The SMS may come from a variety of numbers based on carrier or network the code was sent with. It cannot be customized.

**Comment by BilalReffas** [comment]
![bildschirmfoto 2016-08-29 um 18 43 19](https://cloud.githubusercontent.com/assets/8920003/18059253/7b3e8160-6e18-11e6-9a1f-c396f1968350.png)

What about this example ?

**Comment by olgaikuznetsova** [comment]
The contents of the SMS sent as well as the number it is sent from are not customizable.
