### ISSUE TITLE
Invalid OAuth 2.0 Access Token

### ISSUE THREAD

**Issue by luismenfer** [fbsamples/account-kit-samples-for-ios#9]
Oficial documentation:

````
<plist version="1.0">
<dict>
  <key>FacebookAppID</key>
  <string>{your-app-id}</string>
  <key>AccountKitClientToken</key>
  <string>{your-account-kit-client-token}</string>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>ak{your-app-id}</string>
      </array>
    </dict>
  </array>
  ...
</dict>
</plist>
````

But examples in this project, CFBundleURLSchemes is not following the scheme shows above.

I allways get Invalid OAuth 2.0 Access Token, and my AccountKitClientToken is correct.

Any suggestion?

**Comment by mcohnen** [comment]
It looks like the sample App is following this pattern, right?

https://github.com/fbsamples/account-kit-samples-for-ios/blob/master/AccountKitSample/AccountKitSample/AccountKitSample-Info.plist#L25-L33
